env: "local" # local, dev, prod
storage_path: "./storage/storage.db" # for sqlite
storage_address: "localhost:5432"
storage_type: "sqlite" # sqlite, postgresql
storage_user: "user_db"
storage_password: "password_db"
log:
  local:
    level: "debug" # debug, info, warn, error
    type: "text" # text, json
  prod:
    level: "info" # debug, info, warn, error
    type: "json" # text, json
http_server:
  address: "localhost:5432"
  timeout: 4s
  idle_timeout: 60s
